In [ ]:
Classification dataset

In [5]:
import pandas as pd

df_class = pd.read_csv("Student_Placement_Skills_2025.csv")

# 先简单检查数据的基本情况，检查数据有多少行多少列，有没有空值和重复值
print("原始数据大小：", df_class.shape)
print("\n每一列的空值数量：")
print(df_class.isnull().sum())
print("\n重复行数量：", df_class.duplicated().sum())

# 统一文字格式
df_class["Gender"] = df_class["Gender"].astype(str).str.strip().str.title()
df_class["Placement_Offer"] = df_class["Placement_Offer"].astype(str).str.strip().str.title()
df_class["Degree"] = df_class["Degree"].astype(str).str.strip()

# 删除 Student_ID，学生编号，对预测没有实际帮助
df_class = df_class.drop(columns=["Student_ID"])

# 把 Gender 变成数字， Male 记为 1，Female 记为 0
df_class["Gender"] = df_class["Gender"].map({"Male": 1, "Female": 0})

#把 Placement_Offer 也变成数字，Yes 记为 1，No 记为 0
df_class["Placement_Offer"] = df_class["Placement_Offer"].map({"Yes": 1, "No": 0})

# 删除 Salary_Offered_USD，这个任务是预测有没有拿到 offer，如果把薪资也放进去，就相当于提前告诉模型结果，不合理
df_class = df_class.drop(columns=["Salary_Offered_USD"])

# 把 Degree 做成 one-hot encoding，因为专业是文字，不能直接给模型使用
df_class = pd.get_dummies(df_class, columns=["Degree"], dtype=int)

# 检查一下处理后的数据
print("\n处理后数据大小：", df_class.shape)
print("\n处理后每一列的空值数量：")
print(df_class.isnull().sum())

# 看前五行，确认数据有没有处理成功
print("\n处理后的前五行数据：")
display(df_class.head())

# 保存成新的 csv 文件
df_class.to_csv("classification_encoded.csv", index=False)

print("\n分类任务的数据已经保存好了：classification_encoded.csv")

原始数据大小： (600, 13)

每一列的空值数量：
Student_ID                        0
Gender                            0
Age                               0
Degree                            0
CGPA                              0
Internships_Count                 0
Projects_Count                    0
Certifications_Count              0
Technical_Skills_Score_100        0
Communication_Skills_Score_100    0
Aptitude_Test_Score_100           0
Placement_Offer                   0
Salary_Offered_USD                0
dtype: int64

重复行数量： 0

处理后数据大小： (600, 15)

处理后每一列的空值数量：
Gender                            0
Age                               0
CGPA                              0
Internships_Count                 0
Projects_Count                    0
Certifications_Count              0
Technical_Skills_Score_100        0
Communication_Skills_Score_100    0
Aptitude_Test_Score_100           0
Placement_Offer                   0
Degree_Arts                       0
Degree_Business                   0
Degree_Computer Science           0
Degree_Data Science               0
Degree_Engineering                0
dtype: int64

处理后的前五行数据：

,Gender,Age,CGPA,Internships_Count,Projects_Count,Certifications_Count,Technical_Skills_Score_100,Communication_Skills_Score_100,Aptitude_Test_Score_100,Placement_Offer,Degree_Arts,Degree_Business,Degree_Computer Science,Degree_Data Science,Degree_Engineering
0,1,19,2.56,3,8,0,64,42,57,1,0,1,0,0,0
1,0,27,3.66,0,5,2,78,54,40,1,0,0,0,0,1
2,1,26,3.73,0,5,1,61,54,49,0,0,0,0,1,0
3,1,18,2.21,2,8,5,66,42,72,1,0,0,1,0,0
4,1,20,2.59,3,9,2,69,50,53,0,0,1,0,0,0

分类任务的数据已经保存好了：classification_encoded.csv

In [ ]:
regression dataset

In [4]:
import pandas as pd

df_reg = pd.read_csv("Student_Placement_Skills_2025.csv")

# 检查原始数据
print("原始数据大小：", df_reg.shape)
print("\n每一列的空值数量：")
print(df_reg.isnull().sum())
print("\n重复行数量：", df_reg.duplicated().sum())

# 统一文字格式
df_reg["Gender"] = df_reg["Gender"].astype(str).str.strip().str.title()
df_reg["Placement_Offer"] = df_reg["Placement_Offer"].astype(str).str.strip().str.title()
df_reg["Degree"] = df_reg["Degree"].astype(str).str.strip()

# 删除 Student_ID
df_reg = df_reg.drop(columns=["Student_ID"])

# 只保留拿到 offer 的学生,薪资预测只对已经拿到 offer 的学生有意义
df_reg = df_reg[df_reg["Placement_Offer"] == "Yes"].copy()

# 把 Gender 变成数字,Male 记为 1，Female 记为 0
df_reg["Gender"] = df_reg["Gender"].map({"Male": 1, "Female": 0})

# 第七步：删除 Placement_Offer,现在留下来的都是 Yes，这一列已经没有作用了
df_reg = df_reg.drop(columns=["Placement_Offer"])

# 把 Degree 做成 one-hot encoding,把文字专业拆成多个 0/1 的列，方便后面建模
df_reg = pd.get_dummies(df_reg, columns=["Degree"], dtype=int)

# 检查处理后的结果
print("\n处理后数据大小：", df_reg.shape)
print("\n处理后每一列的空值数量：")
print(df_reg.isnull().sum())

# 看前五行，确认数据处理有没有成功
print("\n处理后的前五行数据：")
display(df_reg.head())

# 保存成新的 csv 文件
df_reg.to_csv("regression_encoded.csv", index=False)

print("\n回归任务的数据已经保存好了：regression_encoded.csv")

原始数据大小： (600, 13)

每一列的空值数量：
Student_ID                        0
Gender                            0
Age                               0
Degree                            0
CGPA                              0
Internships_Count                 0
Projects_Count                    0
Certifications_Count              0
Technical_Skills_Score_100        0
Communication_Skills_Score_100    0
Aptitude_Test_Score_100           0
Placement_Offer                   0
Salary_Offered_USD                0
dtype: int64

重复行数量： 0

处理后数据大小： (387, 15)

处理后每一列的空值数量：
Gender                            0
Age                               0
CGPA                              0
Internships_Count                 0
Projects_Count                    0
Certifications_Count              0
Technical_Skills_Score_100        0
Communication_Skills_Score_100    0
Aptitude_Test_Score_100           0
Salary_Offered_USD                0
Degree_Arts                       0
Degree_Business                   0
Degree_Computer Science           0
Degree_Data Science               0
Degree_Engineering                0
dtype: int64

处理后的前五行数据：

,Gender,Age,CGPA,Internships_Count,Projects_Count,Certifications_Count,Technical_Skills_Score_100,Communication_Skills_Score_100,Aptitude_Test_Score_100,Salary_Offered_USD,Degree_Arts,Degree_Business,Degree_Computer Science,Degree_Data Science,Degree_Engineering
0,1,19,2.56,3,8,0,64,42,57,8047.08,0,1,0,0,0
1,0,27,3.66,0,5,2,78,54,40,3518.56,0,0,0,0,1
3,1,18,2.21,2,8,5,66,42,72,13946.28,0,0,1,0,0
6,1,25,2.42,4,8,4,50,61,65,14820.55,0,0,0,1,0
8,0,27,3.02,0,3,4,49,84,76,16192.47,0,0,0,0,1

回归任务的数据已经保存好了：regression_encoded.csv